### ISSUE TITLE
Bad merge caused TestCommands.cs.meta to be invalid with `<<< HEAD`  line

### ISSUE THREAD

**Issue by hsandt** [YarnSpinnerTool/YarnSpinner-Unity#284]
**What is the current behavior?**

I see the console warning:

> The GUID inside 'Packages/dev.yarnspinner.unity/Tests/Runtime/CommandDispatchTests/AssemblyDefinition/TestCommands.cs.meta' cannot be extracted by the YAML Parser. Attempting to extract it via string matching instead. Please verify the file does not contain unexpected data.

Inspecting the file shows indeed a bad merge leftover:

```
fileFormatVersion: 2
<<<<<<< HEAD:Tests/Runtime/AssemblyDefinition/TestCommands.cs.meta
guid: 36d12434272144830aed6106488edee7
=======
guid: ca28301cfbfea4c83bae10ed899b6c3c
>>>>>>> a066b5d070402f58ae17de3338d995203e890fcf:Runtime/Views/ViewInputAddon.cs.meta
MonoImporter:
  externalObjects: {}
  serializedVersion: 2
  defaultReferences: []
  executionOrder: 0
  icon: {instanceID: 0}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
```

**Please provide the steps to reproduce, and if possible a minimal demo of the problem**:
Just install Yarn Spinner 2.4.2 and check the output log

**What is the expected behavior?**
No meta file error

**Please tell us about your environment:**
  
  - Yarn Spinner Version: 2.4.2
  - Unity Version:  6000.0.7f1
